# Generated by Django 4.0.4 on 2022-06-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_plt', '0002_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_test_name', models.CharField(max_length=64, verbose_name='用例名称')),
                ('api_test_desc', models.CharField(max_length=64, verbose_name='用例描述')),
                ('api_test_result', models.BooleanField(verbose_name='测试结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('api_tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用例执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_plt.project', verbose_name='测试项目')),
            ],
            options={
                'verbose_name': '用例管理',
                'verbose_name_plural': '用例管理',
            },
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='用例标题')),
                ('api_url', models.CharField(max_length=200, verbose_name='接口地址')),
                ('api_step', models.CharField(max_length=100, null=True, verbose_name='接口地址')),
                ('api_param_value', models.CharField(max_length=800, verbose_name='参数和值')),
                ('api_method', models.CharField(choices=[(1, 'get'), (2, 'post'), (3, 'put'), (4, 'delete'), (5, 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('api_result', models.CharField(max_length=200, verbose_name='预期结果')),
                ('api_response', models.CharField(max_length=5000, null=True, verbose_name='响应数据')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('api_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_mag.apitest', verbose_name='用例名称')),
            ],
        ),
    ]
