# Generated by Django 4.0.4 on 2022-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='api_step',
            field=models.CharField(max_length=100, null=True, verbose_name='测试步骤'),
        ),
    ]
