# Generated by Django 4.0.4 on 2022-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_mag', '0002_alter_apistep_api_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apistep',
            options={'verbose_name': '接口信息', 'verbose_name_plural': '接口信息'},
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api_method',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
    ]
