# Generated by Django 4.0.4 on 2022-06-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_plt', '0002_alter_project_options_project_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField(verbose_name='加入日期')),
                ('role', models.IntegerField(choices=[(1, '测试员'), (2, '测试组长'), (3, '测试经理'), (4, '开发'), (5, '运维'), (6, '项目经理')], verbose_name='角色')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('quit_date', models.DateField(verbose_name='退出日期')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备忘录')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目设置', 'verbose_name_plural': '项目设置'},
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='project_members', through='test_plt.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_plt.project', verbose_name='测试项目'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.CreateModel(
            name='DeployEnv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('hostname', models.CharField(help_text='主机名(IP)', max_length=50, verbose_name='主机名')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备忘录')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_plt.project', verbose_name='测试项目')),
            ],
            options={
                'verbose_name': '部署环境',
                'verbose_name_plural': '部署环境',
            },
        ),
    ]
